### ISSUE TITLE
Issue With Velocity Tracker

### ISSUE THREAD

**Issue by theultrastarter** [viterium/viterium_wallet#2]
Hi i am a developer whos building an crypto wallet app. I forked this repository but i get some issues with the velocictyTracker, anytime i try to debug. Any help?

**Comment by azbuky** [comment]
Flutter v3.x is not supported atm. Use Flutter v2.10.5 instead.

**Comment by theultrastarter** [comment]
Ok sure thank you very much.  Will try it

**Comment by theultrastarter** [comment]
It worked.  But is it possible to change the cain to let's say bsc. Will it be easy implementing that?

**Comment by theultrastarter** [comment]
Hi Azbuky. Wanted to know how I could change the chain to bsc

**Comment by azbuky** [comment]
Viterium is a non-custodial wallet for Vite blockchain. 
Depending on the features you want to implement, adding support for another blockchain like BSC might require substantial work.

**Comment by theultrastarter** [comment]
ok thanks

**Comment by viterium** [comment]
Viterium now uses Flutter 3.7
